name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master]  # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    # Specify the correct docs-folder (where conf.py is located)
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        docs-folder: docs/source    # This must point to the folder containing conf.py
        build-dir: docs/build/html  # Specify where the HTML will be built
