name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master]  # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04

    permissions:
      pages: write
      id-token: write

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Install Python and dependencies
    - name: Set up Python and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    # Step 3: Build the documentation using sphinx-build
    - name: Build Sphinx documentation
      run: |
        sphinx-build docs/source docs/build/html  # Manually build the documentation

    # Step 4: Deploy to GitHub Pages using the built HTML
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html  # Use the correct build directory for HTML files
