name: Deploy Documentation

# Trigger the workflow when pushing to the master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 3: Install dependencies (Sphinx and other required libraries)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx

      # Step 4: Build the Sphinx documentation
      - name: Build docs
        run: |
          cd docs
          make html

      # Step 5: Deploy the generated HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html  
